const rewardNames = {
    'UNIT_A_PUC': 'Presidential Unit Citation',
    'UNIT_B_JMUA': 'Joint Meritorious Unit Award',
    'UNIT_C_VUA': 'Valorous Unit Award',
    'UNIT_D_MUC': 'Meritorious Unit Citation',
    'UNIT_E_ASUA': 'Army Superior Unit Award',
    'A_SS': 'Silver Star',
    'B_DSSM': 'Defense Superior Service Medal',
    'C_LOM': 'Legion of Merit',
    'D_DFC': 'Distinguished Flying Cross',
    'E_SM': 'Soldier\'s Medal',
    'F_BSM': 'Bronze Star Medal',
    'G_PH': 'Purple Heart',
    'H_DMSM': 'Defense Meritorious Service Medal',
    'I_MSM': 'Meritorious Service Medal',
    'J_AM': 'Army Commendation Medal',
    'K_JSCM': 'Joint Service Commendation Medal',
    'L_ACM': 'Air Medal',
    'M_JSAM': 'Joint Service Achievement Medal',
    'N_AAM': 'Army Achievement Medal',
    'O_POWM': 'Prisoner of War Medal',
    'P_GCM': 'Good Conduct Medal',
    'Q_AFEM': 'Armed Forces Expeditionary Medal',
    'R_AFSM': 'Armed Forces Service Medal',
    'S_OVSM': 'Overseas Service Ribbon',
    'T_NCOPDR': 'NCO Professional Development Ribbon',
    'UA_ASR': 'Army Service Ribbon',
    'AAB': 'Air Assault Badge',
    'AAVB': 'Army Aviator Badge',
    'CAB': 'Combat Action Badge',
    'CIB': 'Combat Infantryman Badge',
    'CMD': 'Combat Medical Badge',
    'EOD': 'Explosive Ordnance Disposal Badge',
    'EIB': 'Expert Infantryman Badge',
    'MFF': 'Military Free Fall Parachutist Badge',
    'RQ': 'Rifle Qual. Badge',
    'IB': 'Basic Instructor Badge',
    'IG': 'Senior Instructor Badge',
    'IM': 'Master Instructor Badge',
    'RB': 'Baisc Recruiter Badge',
    'RG': 'Gold Recruiter Badge',
    'RM': 'Master Recruiter Badge'
};

module.exports = rewardNames;
